
            
server:
    port: 8080

spring:
    profiles:
        active: dev
    datasource:
        dataSourceClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/banking
        databaseName: 
        serverName: 
        username: root
        password: 

    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        database: H2
        openInView: false
        show_sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            # hibernate.cache.use_second_level_cache: true
            # hibernate.cache.use_query_cache: false
            # hibernate.generate_statistics: true
            # hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
            